version: "3"

networks:
  batch-network:

services:
  psql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdemo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - batch-network

  batch-app:
    build:
      context: ../
      dockerfile: compose-batch/Dockerfile
    depends_on:
      - psql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql:5432/postgresdemo
    ports:
      - '8080:8080'
    networks:
      - batch-network